# 프로젝트 설정 파일 (YAML 형식)


# Server 설정
server:
  port: 8761  # 포트 번호 (http://localhost:8761)


# Spring Boot 설정
spring:
  # 애플리케이션 설정
  application:
    name: eureka-server # 이름


# Eureka 설정
eureka:
  # Client 설정
  client:
    register-with-eureka: false # Eureka Server 미등록
    fetch-registry: false       # 레지스트리(서비스 목록) 가져오기 비활성화