apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: lgcns

spec:
  # 자원공간의 낭비를 방지하고 관리의 편리성을 제공해주는 옵션!
  revisionHistoryLimit: 2

  replicas: 1
  selector:
    matchLabels:
      app: order  # 서비스에서 찾는 이름

  template:
    metadata:
      labels:
        app: order

    spec:
      # docker container 
      containers:
        - name: order-container
          # ECR 경로
          image: 065656773560.dkr.ecr.us-east-1.amazonaws.com/order-service:latest

          ports:
          - containerPort: 8080

          resources:
            # 컨테이너가 사용할 수 있는 최대치의 리소스
            limits:
              cpu: "1"
              memory: "256Mi"
            # 컨테이너가 기동할 때 보장받는 최소 리소스
            requests:
              cpu: "0.5"
              memory: "256Mi"

          # secret 작성 후 외부 환경변수를 이용해서 파드 실행 시 주입할 예정
          env:
          - name: DB_HOST # application.yml에 있는 이름들
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_HOST
          - name: DB_ADMIN
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_ADMIN
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_PASSWORD

          # # 컨테이너 상태 확인
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080


---

# core service setting
# core group : pod, service, ConfigMap, Secret, namespace
apiVersion: v1 
kind: Service
metadata:
  name: order-service # application.yml에서 찾아가는 이름
  namespace: lgcns
spec:
  type: ClusterIP
  ports:  # 이 port를 맞춰서 서비스가 라우터로 접근 가능
  - port: 80  # 외부 포트 번호
    targetPort: 8080  # 내부 포트 번호
  selector:
    app: order  # 위 selector의 이름과 동일하게