name: deploy order  # setting workflow name

# setting Trigger
on:
  push:       # push main branch
    branches:
      - main

# setting Jobs
jobs:
  # job name
  build-and-deploy:

    # runner
    runs-on: ubuntu-latest

    steps:
      # step 1 : source code checkout
      - name: checkout github
        uses: actions/checkout@v2 # https://docs.github.com/ko/actions

      # step 2 : kubectl client install
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.34.1"

      # step 3 : aws authentication
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1

      # step 4 : aws eks cluster update
      - name: aws eks cluster update
        run: aws eks update-kubeconfig --region us-east-1 --name lgcns-hajihyeok-cluster

      # step 5 : aws ecr login
      - name: aws ecr login
        uses: aws-actions/amazon-ecr-login@v1

      # step 6 : deploy infra (ingress, kafka, redis, zookeeper, rabbitmq)
      - name: deploy infra
        run: |
          kubectl apply -f ./k8s/msa-ingress.yml
          kubectl apply -f ./k8s/msa-zookeeper.yml
          kubectl apply -f ./k8s/msa-kafka.yml
          kubectl apply -f ./k8s/msa-redis.yml

      # step 7 : build and push docker image to ecr
      # apigateway
      - name: apigateway build and push docker image to ecr
        env:
          REGISTRY: 065656773560.dkr.ecr.us-east-1.amazonaws.com
          REPOSITORY: apigateway
          IMAGE_TAG: latest
        run: |
          docker build -t ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG} -f ./apigateway/Dockerfile ./apigateway
          docker push ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

      - name: apigateway kubectl apply
        run: |
          kubectl apply -f ./apigateway/k8s/apygateway-depl.yml
          kubectl rollout restart deployment apigateway-deployment -n lgcns


    #   # step 8
    #   - name: kubectrl apply
    #     run: |
    #       kubectl apply -f k8s/order_redis.yml
    #       kubectl apply -f k8s/order_deployment.yml
    #       kubectl apply -f k8s/order_ingress.yml
    #       kubectl rollout restart deployment order-deployment -n lgcns